apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.config.secrets}}
  namespace: {{.Values.config.namespace}}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets }}
    {{ $k }}: {{ $v | b64enc }}
  {{- end }}