apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.config.namespace}}
  name: {{ include "orders-service.fullname" . }}
  labels:
    {{- include "orders-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "orders-service.selectorLabels" . | nindent 4 }}
